### ISSUE TITLE
Beta Correction

### ISSUE THREAD

**Issue by BenjaminAmbrose** [OpenSMFS/FRETBursts#16]
Hi, is there currently any plans to implement beta correction to the stoichiometry for us-ALEX? I think I might be able to do it but I wanted to ask if this was already being worked on before doing it myself

Thanks!

-Ben

**Comment by tritemio** [comment]
Hi @BenjaminAmbrose, are you referring to the FRET correction functions in `fretmath.py`? If I remember correctly, the implemented formulas for `S` do not include the beta, so that S after correction will be constant with E but not necessary centered around S=0.5. 

For computing the burst size (and thus when selecting burst by size) you can already use the beta factor. See for example [Data.burst_sizes_ich](https://fretbursts.readthedocs.io/en/latest/data_class.html?highlight=burst_sizes_ich#fretbursts.burstlib.Data.burst_sizes_ich).

Anyway, we don't have plan on working on this. You are welcome to send a PR. To avoid wasting time, explain what you intend to do first so I can chime in before you do the work.

**Comment by tritemio** [comment]
Closing since no answer.
