### ISSUE TITLE
Single laser measurement loading and processing?

### ISSUE THREAD

**Issue by khoroshyy** [OpenSMFS/FRETBursts#45]
Hi.
Can I ask you for an example of processing the dataset with a single laser, non-ALEX dataset?
Thanks.
Petro.

**Comment by harripd** [comment]
This is poor Github etiquette, and not how the issues tab of Github is supposed to be used.
Namely, you provide absolutely no details regarding the issues you are having.
When you raise an issue you are supposed to provide details about the problem you are having so that the issue can be understood and reproduced. This is both so that we can help you, but also so that others with the same issue can look at the thread and understand how to solve the issue.
You provide absolutely no details, and someone looking at this thread will not be assisted in any way.
I am therefore closing this issue as resolved.
I further know through conversations with people we both work with that you were specifically asked to email me directly instead of using Github. Email me directly and I will help, but I will not respond on Github further.
